language: cpp
sudo: true
distrib: trusty

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - cat /etc/group
  - cat /etc/fstab
  - sudo addgroup --gid 3003 test
  - sudo addgroup --gid 3004 group1
  - sudo addgroup --gid 3005 group2
  - sudo addgroup --gid 3006 group3
  - sudo addgroup --gid 3007 group4
  - sudo addgroup --gid 3008 group5
  - sudo adduser --home /home/test --shell /usr/bin/mysecureshell --uid 4002 --gid 3003 --disabled-password --gecos "" test
  - sudo adduser --home /home/test2 --shell /usr/bin/mysecureshell --uid 4003 --gid 3003 --disabled-password --gecos "" test2
  - echo 'test:test' | sudo chpasswd
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libacl1-dev libgnutls28-dev acl clang; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 && brew link --force llvm35; fi

before_script:
  - ./configure

script:
  - sudo make install
  - cd tests
  - sudo -E `which mvn` clean package
  - getfacl /home/test/tests/d5

#after_success:
#  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master
    - /^issue\d+/
    - /^v\d+\./

notifications:
  email: false

env:
  global:
    - LANG="en_US.UTF-8"
    - serverHost="localhost"
    - serverUser="test"
    - serverPassword="test"

os:
  - linux
#  - osx

addons:
  coverity_scan:
    project:
      name: mysecureshell/mysecureshell
      description: MySecureShell
    notification_email: $COVERITY_SCAN_EMAIL
    build_command_prepend: ./configure
    build_command: make all
    branch_pattern: master
